---
  - name: install and configure tomcat
    hosts: apache
    gather_facts: false
    become: yes
    vars:
      req_tomcat_ver: 8.5.0
      req_port: 8888
      tomcat_url: https://archive.apache.org/dist/tomcat/tomcat-{{req_tomcat_ver.split('.')[0]}}/v{{req_tomcat_ver}}/bin/apache-tomcat-{{req_tomcat_ver}}.tar.gz
    tasks:
    # update packages
    - name: updating repos
      apt:
        update_cache: yes
        cache_valid_time: 3600
    # Install java
    - name: Installating java
      apt: name=default-jdk state=latest
    # Download tomcat tar file
    - name: downloading required tomcat
      get_url:
        url: "{{tomcat_url}}"
        dest: /usr/local
    # Extract tomcat tar file
    - name: extract downloading tomcat
      unarchive:
        src: "/usr/local/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
        dest: /usr/local
        remote_src: yes
    # copy tomcat-users.xml file
    - name: copy the files
      copy:
        src: tomcatusers.xml
        dest: /usr/local/apache-tomcat-{{req_tomcat_ver}}/conf/tomcat-users.xml
    # Change default port in server.xml
    - name: change port no
      lineinfile:
        path: /usr/local/apache-tomcat-{{req_tomcat_ver}}/conf/server.xml
        regexp: '<Connector port="8080" protocol="HTTP/1.1"'
        line: ' <Connector port="8888" protocol="HTTP/1.1"'
        remote_src: yes
    # Copy context.xml file
    - name: copy the context file
      copy:
        src: context.xml
        dest: /usr/local/apache-tomcat-{{req_tomcat_ver}}/webapps/manager/META-INF
    # Terraform install
    - name: terraform install
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.9.1/terraform_0.9.1_linux_amd64.zip
        dest: /usr/bin
        remote_src: yes
    # Download war files from nexus
    - name: download artifact from nexus server
      get_url:
        url: http://35.154.187.118:8081/repository/my_repo/com/example/Java_app/0-SNAPSHOT/Java_app-0-20230204.174314-2.war
        dest: /opt/tomcat/apache-tomcat-10.0.8/webapps
    # shutdown and start tomcat
    - name: starting tomcat
      shell: /usr/local/apache-tomcat-{{req_tomcat_ver}}/bin/shutdown.sh && nohup /usr/local/apache-tomcat-{{req_tomcat_ver}}/bin/startup.sh
